name: Cache Demo with Secret Test

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use secret safely
        env:
          API_KEY: ${{ secrets.MY_API_KEY }}
        run: |
          echo "Secret is set!"
          echo "Secret length: ${#API_KEY}"
